{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "audit.fullname" . }}
  labels:
    {{- include "audit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`)"
      services:
        - name: {{ include "audit.fullname" . }}-fe
          passHostHeader: true
          port: {{ .Values.service.port }}
      middlewares:
        - name: gzip
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)"
      services:
        - name: {{ include "audit.fullname" . }}-be
          passHostHeader: true
          port: {{ .Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    secretName: cert-{{ include "audit.fullname" . }}
  {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gzip
spec:
  compress: {}

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-{{ include "audit.fullname" . }}
spec:
  secretName: cert-{{ include "audit.fullname" . }}
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    kind: {{ .Values.ingress.certificate.issuerRef.kind }}
    name: {{ .Values.ingress.certificate.issuerRef.name }}
{{- end }}
