name: Build
on: push
jobs:
  build-be:
    name: Build audit-be
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: audit-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - name: Install Dependencies
        run: go mod tidy
      - name: Build
        run: go build -o app .
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            audit-be/app
  build-fe:
    name: Build audit-fe
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: audit-fe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            audit-fe/dist/
            audit-fe/stats.html
